In [3]:
import numpy as np
import pandas as pd

data = pd.read_csv("D:\Data\OPT\convlstm\data11.csv")
df = pd.DataFrame(data)
df.drop(df.columns[[0, 1, 2, 3]], axis=1, inplace=True)
matrix = np.array(df)

matrix = np.delete(matrix, [len(matrix)-1, len(matrix)-2], axis=0)
print(matrix.shape)

(1001, 4)


In [4]:
data = np.empty((139, 5, 7))

count = 0
for i in range(139):
    week = 0
    while(week<5):
        day = 0
        while(day<7):
            data[i][week][day] = matrix[count][0]
            day = day + 1
            count = count + 1
        week = week + 1
    count = count - 28
        
print(data.shape)

(139, 5, 7)


In [5]:
input_data = np.empty((len(data)-4, 5, 5, 7))

for i in range(len(input_data)):
    time_step = 0
    while(time_step<5):
        input_data[i][time_step] = data[i + time_step]
        time_step = time_step + 1
        
print(input_data.shape)

(135, 5, 5, 7)


In [7]:
print(input_data[1][0])

[[3353. 3323. 1860. 1800. 1938. 1744. 2004.]
 [2447. 1746. 1608. 1499. 1666. 1584. 1802.]
 [2335. 2408. 2388. 1983. 1857. 1530. 1471.]
 [1237. 1224. 1298. 1241. 1122.  951.  900.]
 [1290.  928.  844.  712.  813.  773.  899.]]


In [8]:
print(input_data[0][1])

[[3353. 3323. 1860. 1800. 1938. 1744. 2004.]
 [2447. 1746. 1608. 1499. 1666. 1584. 1802.]
 [2335. 2408. 2388. 1983. 1857. 1530. 1471.]
 [1237. 1224. 1298. 1241. 1122.  951.  900.]
 [1290.  928.  844.  712.  813.  773.  899.]]
